Add handbrake-9999

diff --git a/media-video/handbrake/files/handbrake-1.3.0-dont-search-for-python.patch b/media-video/handbrake/files/handbrake-1.3.0-dont-search-for-python.patch
--- a/media-video/handbrake/files/handbrake-1.3.0-dont-search-for-python.patch
+++ b/media-video/handbrake/files/handbrake-1.3.0-dont-search-for-python.patch
@@ -1,27 +1,20 @@
 diff --git a/configure b/configure
-index 5c870e1d7..2f5834083 100755
+index 8eb25346e..f9058e0ac 100755
 --- a/configure
 +++ b/configure
-@@ -14,20 +14,8 @@ inpath()
+@@ -12,13 +12,5 @@ inpath()
+     return 1
  }
  
- if ( inpath bash ); then
--    pp=""
--    for p in python3 python3.8 python3.7 python3.6 python3.5 python3.4 python3.3 python3.2 python3.1 python2 python2.7 python
--    do
--        if ( inpath $p ); then
--            pp="$p"
--            break
--        fi
--    done
--    if [ pp != "" ]; then
--        exec $pp `dirname $0`/make/configure.py "$@"
+-for p in python3 python3.11 python3.10 python3.9 python3.8 python3.7 python3.6 python
+-do
+-    if ( inpath $p ); then
+-        exec $p `dirname $0`/make/configure.py "$@"
 -        exit 0
--    else
--        echo "ERROR: no suitable version of python found."
 -    fi
-+    exec python `dirname $0`/make/configure.py "$@"
-+    exit 0
- else
-     echo "ERROR: bash shell not found."
- fi
+-done
+-
+-echo "ERROR: no suitable version of python found."
+-exit 1
++exec python `dirname $0`/make/configure.py "$@"
++exit 0
